### ISSUE TITLE
vertical-scroll PullingUp loading Don't disappear

### ISSUE THREAD

**Issue by liuxingjun** [ustbhuangyi/better-scroll#552]
### Version
1.11.1

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll/#/examples/vertical-scroll/en](https://ustbhuangyi.github.io/better-scroll/#/examples/vertical-scroll/en)

### Steps to reproduce
Pulling up hidden when there is no data loading

``` css
.scroll-content{
  //......
  transform: translate(0px, -50px) scale(1) translateZ(0px);
//......
}
```
'transform:translate' Should increase 50 px

### What is expected?
Hide the loading

### What is actually happening?
Still showing
