### ISSUE TITLE
移动端chrome浏览器和Safari浏览器，当底部有浮动菜单时，向下滑浏览器的菜单不隐藏，导致划不到最底部

### ISSUE THREAD

**Issue by MaZhaolin** [ustbhuangyi/better-scroll#757]
### Version
1.14.0

### Reproduction link
[https://codesandbox.io/s/z62wyr05xl](https://codesandbox.io/s/z62wyr05xl)

### Steps to reproduce
Safari中打开重现链接，100条数据只能滑动96条左右，测试手机为6s和xr

### What is expected?
可以滑到底部

### What is actually happening?
划不到底部

---
遇到的业务场景为底部有浮动tabbar的情况
另外提issue的地址用不了，点创建内容传不过来，需要手动复制过来

**Comment by MaZhaolin** [comment]
看了一下cube-ui 的JD实例页面也会有这个问题 ，无法滑到底部，地址： https://didi.github.io/cube-ui/example/#/scroll/jd

**Comment by theniceangel** [comment]
看了下你的codesandbox，是因为你布局用了 vh 的原因，可能因为菜单栏的缘故，所以 wrapper 的计算高度变大了。建议使用如下的 css 布局：
```css
.wrapper {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 50px;
}
```
